### ISSUE TITLE
When do you plan to open source the code?

### ISSUE THREAD

**Issue by chengaopro** [ZrrSkywalker/PointCLIP#2]
Interesting work. When do you plan to open source the code?

**Comment by ZrrSkywalker** [comment]
Thanks for your interests. We will release in a few days.

**Comment by machengcheng2016** [comment]
Greetings! When will you release the code?

**Comment by ZrrSkywalker** [comment]
@chengaopro @machengcheng2016 Thanks for your interests. We have released our code.

**Comment by chengaopro** [comment]
Thx!
