### ISSUE TITLE
Zero Learning Question

### ISSUE THREAD

**Issue by DuanhaoranCC** [ZrrSkywalker/PointCLIP#4]
Hello, Zero Learning is to make predictions on categories you don't see. CLIP self supervised training on 400 million picture text pairs will inevitably see categories you don't see. Is this also called Zero Learning? Thank you for your patience.

**Comment by ZrrSkywalker** [comment]
Thanks for the question. We inherit the same zero-shot/few-shot setup following the original CLIP paper, which is, predicting on a new dataset without any in-dataset training. It differs from the traditional query/support set division and is more challenging. Traditional setup trains and tests within the same dataset of different categories, but CLIP and our PointCLIP test on a completely new dataset without considering the categories.
