### ISSUE TITLE
Code for ModelNet 10 and s3dis experiments

### ISSUE THREAD

**Issue by mu-cai** [ZrrSkywalker/PointCLIP#5]
Hi,

This paper is a really interesting work!
I wonder when will you realize the code for ModelNet 10 and s3dis experiments?
Thank you!

**Comment by ZrrSkywalker** [comment]
Thanks for your interest!
We conduct PointCLIP on Model10, Model40 and ScanObjectNN. The codes for Model10 and ScanObjectNN are under wrapping.
