### ISSUE TITLE
The zero-shot classification acc is lower than origin paper

### ISSUE THREAD

**Issue by wangyePHD** [ZrrSkywalker/PointCLIP#7]
Thanks for your wonderful work which is helpful for my research. I found that when I use 'bash zeroshot.sh', the classification acc is about 19.33% (20.18% in your paper). I have tried many times. But the gap still exists. Please help me, thank you again !

**Comment by ZrrSkywalker** [comment]
Thanks for your interests! you can use --post-search in the 'bash zeroshot.sh' searching for the best view weights. It will give 20%+ performance. You can also change "SEARCH/TIME: 4" in the config, e.g. 10 or larger, which leads to finer search and higher accuracy.

**Comment by LinLin1031** [comment]
![image](https://github.com/ZrrSkywalker/PointCLIP/assets/50825626/029cf962-993e-4837-8193-50c11e2525e9)
Thanks for your advice. I have achieved a higher accuracy.
