### ISSUE TITLE
运行代码遇到的问题

### ISSUE THREAD

**Issue by victer123** [ZrrSkywalker/PointCLIP#8]
您好，刚刚下载运行了您的代码，但是运行.sh文件后，日志文件里没有精度。还有一个小问题train.py文件需要运行吗，我运行了一下会报错，希望您有时间解答一下，万分感谢。

**Comment by ZiyuGuo99** [comment]
@victer123 您好，.sh 脚本中的命令即为运行 train.py ，其中包含运行所需的命令行参数。成功运行 .sh 文件后，终端输出的训练/测试过程和结果会同步输出到log文件中。

**Comment by victer123** [comment]
您运行代码的时候是windows系统吗

**Comment by ZiyuGuo99** [comment]
您好，我们使用的是 linux 系统，还未在 windows 系统进行尝试。
